# Generated by Django 2.2 on 2022-02-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='SlotDetails',
            table='slot_time_detail',
        ),
    ]
