# Generated by Django 2.2 on 2022-02-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0003_auto_20220206_2120'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='SlotDetails',
            table='slot_booking_details',
        ),
    ]
