# Generated by Django 2.2 on 2022-02-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0004_auto_20220206_2125'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='SlotDetails',
            table='SlotDetails',
        ),
    ]
